apiVersion: v1
kind: Service
metadata:
  labels:
    app: openvpn-depl
  name: openvpn-svc
  namespace: openvpn
spec:
  ports:
    - port: 943
      name: admin-web
      protocol: TCP
      targetPort: 943
    - port: 443
      name: cleint-web
      protocol: TCP
      targetPort: 443
    - port: 1194
      name: openvpn-udp
      protocol: UDP
      targetPort: 1194
  selector:
    app: openvpn-depl
  type: NodePort
